In [1]:
import os, sys, copy, time, math, random, numbers, itertools, tqdm, importlib, re
import numpy as np
import numpy.ma as ma
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import rasterio
import torch
import yaml
from lightning.pytorch import Trainer
from sklearn import metrics
from skimage import transform as trans
from pathlib import Path
from collections.abc import Sequence
from datetime import datetime, timedelta
from scipy.ndimage import rotate
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import init
from torch import optim
from torch.optim.lr_scheduler import _LRScheduler
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import SubsetRandomSampler
from torch.utils.tensorboard import SummaryWriter

from IPython.core.debugger import set_trace

%load_ext autoreload
%autoreload 2
%matplotlib inline

/home/npatel23/gokhale_ada/users/npatel23/conda_envs/cropclassi/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [2]:

import tempfile

import timm
from lightning.pytorch import Trainer

In [3]:
import rasterio
import numpy as np
# Specify the path to your TIFF file
file_path = 'chip_008_030_2014-01-04.mask.tif'

# Open the TIFF file
with rasterio.open(file_path) as src:
    # Read the raster data as a numpy array
    data = src.read(1)
    print(data)
    print(np.min(data))

[[20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 20]
 ...
 [20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 14]
 [20 20 20 ... 20 20 20]]
9


In [2]:
import rasterio
import numpy as np
# Specify the path to your TIFF file
file_path = 'chip_019_056_2014-02-27.mask.tif'

# Open the TIFF file
with rasterio.open(file_path) as src:
    # Read the raster data as a numpy array
    data = src.read(1)
    print(data)
    print(np.unique(data))

[[3 3 3 ... 4 4 4]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]]
[1 2 3 4]


In [ ]:
Crop Classification Project/Crop_Segmentation_Project/chip_019_056_2014-02-27.mask.tif